rp2_num_steps: 2000
rp2_step_size: 0.1
rp2_num_eot: 5
rp2_optimizer: 'adam'
rp2_lambda: 0
rp2_min_conf: 0
rp2_augment_real: False
attack_mode: ''
no_transform: True
relighting: False
interp: 'bilinear'