rp2_num_steps: 1000
rp2_step_size: 0.01
rp2_num_eot: 1
rp2_optimizer: 'adam'
rp2_lambda: 0
rp2_min_conf: 0
rp2_augment_real: False
attack_mode: ''
no_transform: False
no_relighting: False
interp: 'bilinear'