rp2:
  num_steps: 1000
  step_size: 0.01
  num_eot: 1
  optimizer: 'adam'  # 'adam', 'sgd', 'pgd'
  lambda: 0
  min_conf: 0
  augment_prob_geometric: 1
  augment_prob_relight: 0
  use_patch_relight: True
  patch_dim: 256
  num_bg: 50  # Number of backgrounds attacker uses to generate patch
  use_lr_schedule: False
  transform_mode: 'perspective'
  # var_change_ab: Use variable change on alpha, beta 
  # attack_mode: 'var_change_ab'
  attack_mode: ''

detectron:
  obj_loss_const: 0
  iou_thres: 0

# Shapeshifter attack
# https://github.com/shangtse/robust-physical-attack/blob/master/Makefile#L76
# rp2:
#   min_conf: 0
#   augment_prob_geometric: 1
#   augment_prob_relight: 0
# detectron:
#   obj_loss_const: 0
#   iou_thres: 0