rp2_num_steps: 1000
rp2_step_size: 0.1
rp2_num_eot: 1
rp2_optimizer: 'adam'
rp2_lambda: 0
rp2_min_conf: 0
rp2_augment_real: False   # Augment when attacking real signs
use_patch_relight: True
num_bg: 5  # Number of backgrounds attacker uses to generate patch
use_lr_schedule: False
transform_mode: 'perspective'
# shapeshifter: Use ShapeShifter loss to attack Faster R-CNN
# var_change_ab: Use variable change on alpha, beta 
# attack_mode: 'shapeshifter-var_change_ab'
attack_mode: 'shapeshifter'
# attack_mode: ''