rp2_num_steps: 1000
rp2_step_size: 0.1
rp2_num_eot: 2
rp2_optimizer: 'adam'
rp2_lambda: 0
rp2_min_conf: 0
rp2_augment_real: False   # Augment when attacking real signs
use_patch_transform: True
use_patch_relight: True
num_bg: 1  # Number of the attacker uses to generate patch
# shapeshifter: Use ShapeShifter loss to attack Faster R-CNN
# var_change_ab: Use variable change on alpha, beta 
attack_mode: 'shapeshifter-var_change_ab'
# interp: 'bilinear'  # This is only used when args.interp is None
