rp2_num_steps: 500
rp2_step_size: 0.01
rp2_num_eot: 1
rp2_optimizer: 'adam'
rp2_lambda: 0
rp2_min_conf: 0.
use_augment: False   # Augment when attacking real signs
pgd_step_size: 0.01
detectron_obj_const: 1
use_patch_relight: True
patch_dim: 32
num_bg: 1  # Number of backgrounds attacker uses to generate patch
use_lr_schedule: False
transform_mode: 'perspective'
# shapeshifter: Use ShapeShifter loss to attack Faster R-CNN
# var_change_ab: Use variable change on alpha, beta 
# attack_mode: 'shapeshifter-var_change_ab'
# attack_mode: 'shapeshifter'
attack_mode: ''