rp2:
  num_steps: 1000
  step_size: 0.01
  num_eot: 1
  optimizer: 'adam'  # 'adam', 'sgd', 'pgd'
  lambda: 0
  min_conf: 0.
  augment_prob: 0
  use_patch_relight: True
  patch_dim: 32
  num_bg: 1  # Number of backgrounds attacker uses to generate patch
  use_lr_schedule: False
  transform_mode: 'perspective'
  # shapeshifter: Use ShapeShifter loss to attack Faster R-CNN
  # var_change_ab: Use variable change on alpha, beta 
  # attack_mode: 'shapeshifter-var_change_ab'
  # attack_mode: 'shapeshifter'
  attack_mode: ''

detectron:
  obj_loss_const: 1
  iou_thres: 0.