# This file is copied directly from
# https://github.com/facebookresearch/detectron2/blob/main/configs/COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml

_BASE_: "./Base-RCNN-FPN.yaml"  # EDIT: path
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  RPN:
    BATCH_SIZE_PER_IMAGE: 256
    POSITIVE_FRACTION: 0.5  # EDIT: default: 0.5
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 512
    POSITIVE_FRACTION: 0.75  # EDIT: default: 0.25
SOLVER:
  # STEPS: (210000, 250000)
  # MAX_ITER: 270000
  BASE_LR: 0.01  # EDIT
  STEPS: (50000, 70000, 90000)  # EDIT
  MAX_ITER: 100000  # EDIT
  IMS_PER_BATCH: 32
INPUT:
  RANDOM_FLIP: 'none'  # EDIT: traffic sign can't be flipped
  MIN_SIZE_TRAIN: (0, )  # TODO: does this disables resizing? If not working, see https://github.com/facebookresearch/detectron2/issues/2275
  MAX_SIZE_TRAIN: 4096
  MIN_SIZE_TEST: 2048   
  MAX_SIZE_TEST: 2048
  CROP:
    TYPE: 'absolute'
    SIZE: (1000, 1000)
DATALOADER:
  NUM_WORKERS: 64
  SAMPLER_TRAIN: 'RepeatFactorTrainingSampler'  # EDIT: default: 'TrainingSampler'
  REPEAT_THRESHOLD: 1.0  # EDIT: default: 0
